### ISSUE TITLE
Getting an error on game load with this active

### ISSUE THREAD

**Issue by khamseen** [WesternGamer/ProperGPSMarkerScaling#1] opened 2023-06-21 00:31 UTC
Looks like this directory and file do not exist in my AppData\Roaming\SpaceEngineers\ directory. 

[PluginLoader] Failed to initialize WesternGamer/ProperGPSMarkerScaling|GPS Marker Scaling because of an error: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\xxxxxx\AppData\Roaming\SpaceEngineers\Storage\PluginData\GpsMarkerScaling.cfg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at ClientPlugin.Config.PersistentConfig`1.Save(String path)
   at ClientPlugin.Config.PersistentConfig`1.Load(String path)
   at ClientPlugin.Plugin.Init(Object gameInstance)
   at avaness.PluginLoader.PluginInstance.Init(Object gameInstance)

**Comment by WesternSpace** [comment] 2023-06-21 00:33
I know what the issue is, should be fixed in an hour.

**Comment by khamseen** [comment] 2023-06-21 00:40
Awesome, wasn't expecting such a quick response. Thanks man!

**Comment by WesternSpace** [comment] 2023-06-26 02:39
Sorry that this took longer than expected, but I released a bug fix today that fixed the issue. It should be published within a hour.

**Closed as completed by WesternSpace** 2023-06-26 02:39 UTC

**Comment by khamseen** [comment] 2023-06-29 23:05
I kept forgetting to add the plugin again after your fix but eventually remembered today and it's all working great! Thanks for the fix, the PS5 update which made them all huge on 4K was super annoying.
